version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'handred'
      MYSQL_ROOT_PASSWORD: 'handred'
    networks:
      default:
        aliases:
          - db.local
    ports:
      - '127.0.0.1:3306:3306'

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
    driver: local
